export const ANSWER_FETCHING = 'ANSWER_FETCHING';
export const ANSWER_FETCHING_ERROR = 'ANSWER_FETCHING_ERROR';
export const ANSWER_FETCHING_SUCCESS = 'ANSWER_FETCHING_SUCCESS';

export const ADD_USER_ANSWER = 'ADD_USER_ANSWER';

export const MESSAGE_LIST_UPDATED_HANDLED = "MESSAGE_LIST_UPDATED_HANDLED";

export const RESET_MESSAGE_LIST = 'RESET_MESSAGE_LIST';