export const UPDATE_TITLE = 'UPATE_TITLE';
export const UPDATE_SHORT_DESCRIPTION = 'UPDATE_SHORT_DESCRIPTION';
export const UPDATE_SECTION_NAME = 'UPDATE_SECTION_NAME';
export const UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION';
export const UPDATE_QUIZ_TITLE = 'UPDATE_QUIZ_TITLE';
export const UPDATE_LEVEL = 'UPDATE_LEVEL';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const UPDATE_POSSIBLE_ANSWER = 'UPDATE_POSSIBLE_ANSWER';

export const DELETE_COURSE = 'DELETE_COURSE';
export const DELETE_SECTION = 'DELETE_SECTION';
export const DELETE_DESCRIPTION = 'DELETE_DESCRIPTION';
export const DELETE_QUIZ = 'DELETE_QUIZ';
export const DELETE_LEVEL = 'DELETE_LEVEL';
export const DELETE_QUESTION = 'DELETE_QUESTION';

export const ADD_COURSE = 'ADD_COURSE';
export const ADD_SECTION = 'ADD_SECTION';
export const ADD_DESCRIPTION = 'ADD_DESCRIPTION';
export const ADD_QUIZ = 'ADD_QUIZ';
export const ADD_LEVEL = 'ADD_LEVEL';
export const ADD_QUESTION = 'ADD_QUESTION';

export const COURSES_FETCHING = 'COURSES_FETCHING';
export const COURSES_FETCHING_ERROR = 'COURSES_FETCHING_ERROR';
export const COURSES_FETCHING_SUCCESS = 'COURSES_FETCHING_SUCCESS';


export const FETCH_JSON = 'FETCH_JSON';