export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT = "LOGOUT";
export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const SET_LOGGED_OUT = "SET_LOGGED_OUT";

export const REQUESTING_NEW_PASSWORD = 'REQUESTING_NEW_PASSWORD';
export const REQUESTING_NEW_PASSWORD_ERROR = 'REQUESTING_NEW_PASSWORD_ERROR';
export const REQUESTING_NEW_PASSWORD_SUCCESS = 'REQUESTING_NEW_PASSWORD_SUCCESS';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const REQUEST_VERIFICATION = 'REQUEST_VERIFICATION';
export const REQUEST_VERIFICATION_ERROR = 'REQUEST_VERIFICATION_ERROR';
export const REQUEST_VERIFICATION_SUCCESS = 'REQUEST_VERIFICATION_SUCCESS';