export const FETCH_PAGE_DATA = 'FETCH_PAGE_DATA';
export const FETCH_PAGE_DATA_ERROR = 'FETCH_PAGE_DATA_ERROR';
export const FETCH_PAGE_DATA_SUCCESS = 'FETCH_PAGE_DATA_SUCCESS';

export const UPDATE_FIELD_DATA = 'UPDATE_FIELD_DATA';
export const UPDATE_FIELD_DATA_ERROR = 'UPDATE_FIELD_DATA_ERROR';
export const UPDATE_FIELD_DATA_SUCCESS = 'UPDATE_FIELD_DATA_SUCCESS';