export const FETCH_PAGE_DATA = 'FETCH_PAGE_DATA';
export const FETCH_PAGE_DATA_ERROR = 'FETCH_PAGE_DATA_ERROR';
export const FETCH_PAGE_DATA_SUCCESS = 'FETCH_PAGE_DATA_SUCCESS';

export const UPDATE_FIELD_DATA = 'UPDATE_FIELD_DATA';
export const UPDATE_FIELD_DATA_ERROR = 'UPDATE_FIELD_DATA_ERROR';
export const UPDATE_FIELD_DATA_SUCCESS = 'UPDATE_FIELD_DATA_SUCCESS';

export const TOGGLE_LOG_IN_MODAL = "TOGGLE_LOG_IN_MODAL";

export const COURSE_CREATION_ADD_SECTION = "COURSE_CREATION_ADD_SECTION";
export const COURSE_CREATION_ADD_SECTION_ERROR = "COURSE_CREATION_ADD_SECTION_ERROR";
export const COURSE_CREATION_ADD_SECTION_SUCCESS = "COURSE_CREATION_ADD_SECTION_SUCCESS";

export const COURSE_CREATION_ADD_QUESTION = "COURSE_CREATION_ADD_QUESTION";
export const COURSE_CREATION_ADD_QUESTION_ERROR = "COURSE_CREATION_ADD_QUESTION_ERROR";
export const COURSE_CREATION_ADD_QUESTION_SUCCESS = "COURSE_CREATION_ADD_QUESTION_SUCCESS";

export const COURSE_CREATION_ADD_ANSWER = "COURSE_CREATION_ADD_ANSWER";
export const COURSE_CREATION_ADD_ANSWER_ERROR = "COURSE_CREATION_ADD_ANSWER_ERROR";
export const COURSE_CREATION_ADD_ANSWER_SUCCESS = "COURSE_CREATION_ADD_ANSWER_SUCCESS";

export const COURSE_CREATION_QUESTION_CHANGE_HANDLER = "COURSE_CREATION_QUESTION_CHANGE_HANDLER";
export const COURSE_CREATION_QUESTION_CHANGE_HANDLER_ERROR = "COURSE_CREATION_QUESTION_CHANGE_HANDLER_ERROR";
export const COURSE_CREATION_QUESTION_CHANGE_HANDLER_SUCCESS = "COURSE_CREATION_QUESTION_CHANGE_HANDLER_SUCCESS";

export const COURSE_CREATION_ANSWER_CHANGE_HANDLER = "COURSE_CREATION_ANSWER_CHANGE_HANDLER";
export const COURSE_CREATION_ANSWER_CHANGE_HANDLER_ERROR = "COURSE_CREATION_ANSWER_CHANGE_HANDLER_ERROR";
export const COURSE_CREATION_ANSWER_CHANGE_HANDLER_SUCCESS = "COURSE_CREATION_ANSWER_CHANGE_HANDLER_SUCCESS";

export const COURSE_CREATION_INFORMATION_TEXT_CHANGE_HANDLER = "COURSE_CREATION_INFORMATION_TEXT_CHANGE_HANDLER";
export const COURSE_CREATION_INFORMATION_TEXT_CHANGE_HANDLER_ERROR = "COURSE_CREATION_INFORMATION_TEXT_CHANGE_HANDLER_ERROR";
export const COURSE_CREATION_INFORMATION_TEXT_CHANGE_HANDLER_SUCCESS = "COURSE_CREATION_INFORMATION_TEXT_CHANGE_HANDLER_SUCCESS";

export const COURSE_CREATION_SET_SELECTED_ANSWER = "COURSE_CREATION_SET_SELECTED_ANSWER";
export const COURSE_CREATION_SET_SELECTED_ANSWER_ERROR = "COURSE_CREATION_SET_SELECTED_ANSWER_ERROR";
export const COURSE_CREATION_SET_SELECTED_ANSWER_SUCCESS = "COURSE_CREATION_SET_SELECTED_ANSWER_SUCCESS";

export const COURSE_CREATION_SET_SECTION_TYPE_INFORMATION = "COURSE_CREATION_SET_SECTION_TYPE_INFORMATION";
export const COURSE_CREATION_SET_SECTION_TYPE_INFORMATION_ERROR = "COURSE_CREATION_SET_SECTION_TYPE_INFORMATION_ERROR";
export const COURSE_CREATION_SET_SECTION_TYPE_INFORMATION_SUCCESS = "COURSE_CREATION_SET_SECTION_TYPE_INFORMATION_SUCCESS";

export const COURSE_CREATION_SET_SECTION_TYPE_QUIZ = "COURSE_CREATION_SET_SECTION_TYPE_QUIZ";
export const COURSE_CREATION_SET_SECTION_TYPE_QUIZ_ERROR = "COURSE_CREATION_SET_SECTION_TYPE_QUIZ_ERROR";
export const COURSE_CREATION_SET_SECTION_TYPE_QUIZ_SUCCESS = "COURSE_CREATION_SET_SECTION_TYPE_QUIZ_SUCCESS";

export const COURSE_CREATION_SET_QUESTION_INDEX = "COURSE_CREATION_SET_QUESTION_INDEX";
export const COURSE_CREATION_SET_QUESTION_INDEX_ERROR = "COURSE_CREATION_SET_QUESTION_INDEX_ERROR";
export const COURSE_CREATION_SET_QUESTION_INDEX_SUCCESS = "COURSE_CREATION_SET_QUESTION_INDEX_SUCCESS";

export const COURSE_CREATION_DELETE_SECTION = "COURSE_CREATION_DELETE_SECTION";
export const COURSE_CREATION_DELETE_SECTION_ERROR = "COURSE_CREATION_DELETE_SECTION_ERROR";
export const COURSE_CREATION_DELETE_SECTION_SUCCESS = "COURSE_CREATION_DELETE_SECTION_SUCCESS";

export const COURSE_CREATION_DELETE_QUESTION = "COURSE_CREATION_DELETE_QUESTION";
export const COURSE_CREATION_DELETE_QUESTION_ERROR = "COURSE_CREATION_DELETE_QUESTION_ERROR";
export const COURSE_CREATION_DELETE_QUESTION_SUCCESS = "COURSE_CREATION_DELETE_QUESTION_SUCCESS";

export const COURSE_CREATION_DELETE_ANSWER = "COURSE_CREATION_DELETE_ANSWER";
export const COURSE_CREATION_DELETE_ANSWER_ERROR = "COURSE_CREATION_DELETE_ANSWER_ERROR";
export const COURSE_CREATION_DELETE_ANSWER_SUCCESS = "COURSE_CREATION_DELETE_ANSWER_SUCCESS";